// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ubtwbfbgaaqcmnhapnqa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVidHdiZmJnYWFxY21uaGFwbnFhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1MDEyNDgsImV4cCI6MjA3MDA3NzI0OH0.MyNaQ-WXQVlPo8hXL4Ym2-5w_Q9qoyxnNlGcEMW4SGs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});